name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Chroniq.
title: "[Bug]: "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🐞 **Thanks for reporting a bug in Chroniq! Let’s squash it.**

  - type: input
    id: version
    attributes:
      label: Chroniq Version
      description: Use `chroniq version` to get the current version.
      placeholder: "e.g. 0.9.0"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Be as detailed as possible. If you can, include exact CLI commands.
      placeholder: |
        1. Run `chroniq init`
        2. Then `chroniq bump patch`
        3. Observe the error message...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected the version to bump and update the changelog...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: The changelog was not updated...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Paste logs, stack traces, or screenshots here.
      render: shell
      placeholder: |
        Error: AttributeError: 'tuple' object has no attribute 'get'
    validations:
      required: false
